version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - urlnet

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - urlnet

volumes:
  redis_data:

networks:
  urlnet:
